name: fxmpp
description: A Flutter plugin for XMPP (Extensible Messaging and Presence Protocol) communication, supporting both iOS and Android platforms.
version: 1.0.0-alpha
homepage: https://hainguyen.dev
repository: https://github.com/haithngn/fxmpp

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.hainguyen.fxmpp
        pluginClass: FxmppPlugin
      ios:
        pluginClass: FxmppPlugin

topics:
  - xmpp
  - messaging
  - chat
  - communication
  - real-time
